# Generated by Django 5.2.6 on 2026-04-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentactivity",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
