# Generated by Django 5.2.6 on 2026-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        ("students", "0003_alter_studentactivity_student"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studentactivity",
            constraint=models.UniqueConstraint(
                fields=("student",), name="unique_student_activity"
            ),
        ),
    ]
