# Generated by Django 6.0.1 on 2026-04-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentactivity_unique_student_activity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentactivity',
            name='unique_student_activity',
        ),
    ]
