# Generated by Django 5.2.6 on 2026-04-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentactivity_unique_student_activity'),
        ('students', '0005_student_smart_card_id'),
    ]

    operations = [
    ]
