# Generated by Django 5.2.6 on 2026-04-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_merge_20260407_1714'),
        ('students', '0006_merge_20260407_1736'),
    ]

    operations = [
    ]
