# Generated by Django 6.0.1 on 2026-04-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAnnouncement',
        ),
    ]
