# Generated by Django 6.0.1 on 2026-04-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAnnouncement',
        ),
    ]
