# Generated by Django 6.0.1 on 2026-04-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
